services:
  fe16-tools:
    image: brufinus/fe16-tools
    build:
      context: .
      target: build-dev
    container_name: fe16-tools
    environment:
      - SECRET_KEY=my-secret-key
    ports:
      - "5000:5000"
