"""gift and liked gifts tables

Revision ID: 0086303a3c62
Revises: 6e917aa24cc2
Create Date: 2024-10-09 10:31:41.513201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0086303a3c62'
down_revision = '6e917aa24cc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gift', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gift_name'), ['name'], unique=True)

    op.create_table('liked_gifts',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('gift_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['gift_id'], ['gift.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'gift_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('liked_gifts')
    with op.batch_alter_table('gift', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gift_name'))

    op.drop_table('gift')
    # ### end Alembic commands ###
