"""menu and likedmeals tables

Revision ID: 400fff39f557
Revises: 1fa698f109b4
Create Date: 2024-10-02 23:35:54.606089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '400fff39f557'
down_revision = '1fa698f109b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menu_meal'), ['meal'], unique=True)

    op.create_table('liked_meal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('liked_meal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_liked_meal_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_liked_meal_menu_id'), ['menu_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liked_meal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_liked_meal_menu_id'))
        batch_op.drop_index(batch_op.f('ix_liked_meal_character_id'))

    op.drop_table('liked_meal')
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_meal'))

    op.drop_table('menu')
    # ### end Alembic commands ###
