"""lost item table

Revision ID: 6e917aa24cc2
Revises: bc1312588d85
Create Date: 2024-10-09 00:25:53.508462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e917aa24cc2'
down_revision = 'bc1312588d85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lost_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lost_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lost_item_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lost_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lost_item_name'))

    op.drop_table('lost_item')
    # ### end Alembic commands ###
