"""add grade column to seed

Revision ID: 9493108fd8b7
Revises: 2088e82667b0
Create Date: 2024-10-10 19:57:09.943128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9493108fd8b7'
down_revision = '2088e82667b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seed', schema=None) as batch_op:
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
