"""tea table

Revision ID: a32d44a784f0
Revises: ac74c07f94f1
Create Date: 2024-10-07 19:42:21.161792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a32d44a784f0'
down_revision = 'ac74c07f94f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tea', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tea_name'), ['name'], unique=True)

    op.create_table('liked_teas',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('tea_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['tea_id'], ['tea.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'tea_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('liked_teas')
    with op.batch_alter_table('tea', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tea_name'))

    op.drop_table('tea')
    # ### end Alembic commands ###
