"""tea topic table

Revision ID: adcbf687bd4f
Revises: a32d44a784f0
Create Date: 2024-10-07 21:22:52.756755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adcbf687bd4f'
down_revision = 'a32d44a784f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tea_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tea_topic', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tea_topic_data'), ['data'], unique=True)

    op.create_table('liked_tea_topics',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['tea_topic.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'topic_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('liked_tea_topics')
    with op.batch_alter_table('tea_topic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tea_topic_data'))

    op.drop_table('tea_topic')
    # ### end Alembic commands ###
