"""move liked meals to association table setup

Revision ID: d0d1a85bb248
Revises: 400fff39f557
Create Date: 2024-10-03 23:19:57.224092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0d1a85bb248'
down_revision = '400fff39f557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liked_meals',
    sa.Column('diner_id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diner_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['dish_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('diner_id', 'dish_id')
    )
    with op.batch_alter_table('liked_meal', schema=None) as batch_op:
        batch_op.drop_index('ix_liked_meal_character_id')
        batch_op.drop_index('ix_liked_meal_menu_id')

    op.drop_table('liked_meal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liked_meal',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('character_id', sa.INTEGER(), nullable=False),
    sa.Column('menu_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('liked_meal', schema=None) as batch_op:
        batch_op.create_index('ix_liked_meal_menu_id', ['menu_id'], unique=False)
        batch_op.create_index('ix_liked_meal_character_id', ['character_id'], unique=False)

    op.drop_table('liked_meals')
    # ### end Alembic commands ###
