name: Release and Docker Publish
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/github
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}
          docker build -t brufinus/fe16-tools .
          docker tag brufinus/fe16-tools brufinus/fe16-tools:v${{ steps.semantic.outputs.new_release_version }}

      - name: Push Docker image to Docker Hub
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u brufinus --password-stdin
          docker push brufinus/fe16-tools
          docker push brufinus/fe16-tools:v${{ steps.semantic.outputs.new_release_version }}

